language: java

jdk:
  - oraclejdk7

compiler:
  - clang

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test

packages:
    - clang-3.6

before_script:
    - chmod u+x runtests.sh

script:
    - ./runtests.sh
