language: java

jdk:
  - oraclejdk7
compiler:
  - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install clang-3.7 -qq

before_script:
    - chmod u+x runtests.sh

script:
    - ./runtests.sh
