language: java

jdk:
  - oraclejdk7
  - openjdk7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install clang-3.5 -qq

before_script:
    - chmod u+x runtests.sh

script:
    - ./runtests.sh
